### ISSUE TITLE
PAPI CUDA: CUDA test build failure

### ISSUE THREAD

**Issue by jrodgers-github** [icl-utk-edu/papi#127] opened 2023-11-27 21:36 UTC
Encountering the following PAPI CUDA test build failure on SLES15 platforms using GCC 12:
```
cudaOpenMP.o:(.eh_frame+0x227): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:53: cudaOpenMP] Error 1
```

To prevent this failure, `-lstdc++` can be added to `CUDALIBS` on line 26 of `src/components/cuda/tests/Makefile`, example:
```
CUDALIBS = -L$(PAPI_CUDA_ROOT)/lib64 -lcudart -lcuda -lstdc++
```
- Note: this same option is applied to `CUDALIBS` in `src/components/nvml/tests/Makefile`.

**Comment by jrodgers-github** [comment] 2023-11-27 21:37
Attn: @anustuvicl

**Comment by Treece-Burgess** [comment] 2024-09-28 00:10
@jrodgers-github Is this an issue that you are still experiencing?

**Comment by jrodgers-github** [comment] 2024-09-30 15:47
@Treece-Burgess, unfortunately the systems I have to test on are in constant flux, so I can't fully reproduce the original behavior. 
 However, using SLES 15 SP5 and GCC 12 (ver. 12.2.0) I'm unable to reproduce this issue.

Please let me know if there's any additional information I can provide to help!

**Comment by Treece-Burgess** [comment] 2024-09-30 17:27
@jrodgers-github I understand, apologies for the late reply on the original issue. Since you are unable to reproduce with SLES 15 SP5 and GCC 12 I am going to go ahead and close this issue. If you run into any other issues or this issue crops up again please reach out.

**Closed by Treece-Burgess** 2024-09-30 17:27 UTC
