### ISSUE TITLE
cuda component test code does not deal properly with gcc -spec option

### ISSUE THREAD

**Issue by wcohen** [icl-utk-edu/papi#214] opened 2024-08-05 01:17 UTC
I have been experimenting with local rpmbuilds of papi with the cuda component enabled.  One of the issues I noticed is that RPM build process uses spec files passed into the compiler with the [-specs option](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html#index-specs).  In the spec override files are options to turn on position independent code / executable (PIC/PIE).  Those options are not passed to nvcc, so when attempting to link the cuda test code end up with:

```
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -g -ccbin='gcc' -DPAPI     -c -o HelloWorld.o HelloWorld.cu
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer   -DHAVE_CUDA -DHAVE_NVML -DPAPI_NUM_COMP=16 -g -DPAPI     -o HelloWorld HelloWorld.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/bin/ld: HelloWorld.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:66: HelloWorld] Error 1
```

The above is cause by the -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 and -specs=/usr/lib/rpm/redhat/redhat-hardened-ld being passed in for linking.  redhat-hardened-cc1:

```
*cc1_options:
+ %{!r:%{!fpie:%{!fPIE:%{!fpic:%{!fPIC:%{!fno-pic:-fPIE}}}}}}

*cpp_options:
+ %{!r:%{!fpie:%{!fPIE:%{!fpic:%{!fPIC:%{!fno-pic:-fPIE}}}}}}

```

The redhat-hardened-ld is similar:

```
*self_spec:
+ %{!static:%{!shared:%{!r:-pie}}}

```

As a workaround I added the following to NVCFLAGS:

` -Xcompiler -fpic`

This is probably not quite the right solution as some builds might not be building code as PIE/PIC code.

**Comment by jagode** [comment] 2024-09-20 22:48
@adanalis , you looked into this a couple of weeks ago, correct? Are there any updates on this?

**Comment by adanalis** [comment] 2024-09-23 19:06
Will, I can't reproduce the problem. I configured PAPI with:
./configure --with-shared-lib=yes --with-shlib-tools --with-static-lib=no --with-components=cuda

Everything built fine, including the CUDA tests. I understand that this is not the same setup as your case, since we don't pass those "-specs=..." flags to the compiler/linker.  To simulate your use case, I manually added "-fPIC -fPIE" to my gcc linking, without changing the nvcc compilation, but that still worked without a problem. For reference, here are the two lines on our machine.

/apps/spacks/2024-07-19/opt/spack/linux-rocky9-x86_64/gcc-11.4.1/cuda-11.8.0-q6jpi3of5v7cawdtdr6rldslzmqn7jgb/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/local/include -I/apps/spacks/2024-07-19/opt/spack/linux-rocky9-x86_64/gcc-11.4.1/cuda-11.8.0-q6jpi3of5v7cawdtdr6rldslzmqn7jgb/include -g -ccbin='gcc' -DPAPI     -c -o HelloWorld.o HelloWorld.cu

gcc -DPAPI_NUM_COMP=4 -g -DPAPI -fPIC -fPIE -o HelloWorld HelloWorld.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.2.0.0b1 -L../../../libpfm4/lib -lpfm -L/apps/spacks/2024-07-19/opt/spack/linux-rocky9-x86_64/gcc-11.4.1/cuda-11.8.0-q6jpi3of5v7cawdtdr6rldslzmqn7jgb/lib64 -lcudart -lcuda -Wl,-rpath=/home/adanalis/papi-adanalis-fork/src/libpfm4/lib:/home/adanalis/papi-adanalis-fork/src,--enable-new-dtags

The GCC I'm using is: gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)

Can you help me reproduce the problem?

**Comment by wcohen** [comment] 2024-09-25 18:23
I think that the issue is that the .o files need to be build as position independent code rather than just using pic options when linking.  Below is an example of of the compliles for the cuda tests with the workaround patch:

```
make[1]: Entering directory '/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/components/cuda/tests'
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o HelloWorld.o HelloWorld.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o HelloWorld HelloWorld.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o simpleMultiGPU.o simpleMultiGPU.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o simpleMultiGPU simpleMultiGPU.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o pthreads.o pthreads.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o pthreads pthreads.o -lpthread ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o cudaOpenMP.o cudaOpenMP.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o cudaOpenMP cudaOpenMP.o -lgomp -fopenmp ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o concurrent_profiling.o concurrent_profiling.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
g++ -g -DPAPI     -o concurrent_profiling concurrent_profiling.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o test_multi_read_and_reset.o test_multi_read_and_reset.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o test_multi_read_and_reset test_multi_read_and_reset.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o test_multipass_event_fail.o test_multipass_event_fail.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o test_multipass_event_fail test_multipass_event_fail.o -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags  -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o test_2thr_1gpu_not_allowed.o test_2thr_1gpu_not_allowed.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o test_2thr_1gpu_not_allowed test_2thr_1gpu_not_allowed.o -lpthread ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o concurrent_profiling_noCuCtx.o concurrent_profiling_noCuCtx.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
g++ -g -DPAPI     -o concurrent_profiling_noCuCtx concurrent_profiling_noCuCtx.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o pthreads_noCuCtx.o pthreads_noCuCtx.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o pthreads_noCuCtx pthreads_noCuCtx.o -lpthread ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o cudaOpenMP_noCuCtx.o cudaOpenMP_noCuCtx.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o cudaOpenMP_noCuCtx cudaOpenMP_noCuCtx.o -lgomp -fopenmp ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o HelloWorld_noCuCtx.o HelloWorld_noCuCtx.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o HelloWorld_noCuCtx HelloWorld_noCuCtx.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
/usr/local/cuda-12.5/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.5/include -arch=native -ccbin='gcc' -g -DPAPI     -Xcompiler -fpic -c -o simpleMultiGPU_noCuCtx.o simpleMultiGPU_noCuCtx.cu
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
gcc -g -DPAPI     -o simpleMultiGPU_noCuCtx simpleMultiGPU_noCuCtx.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,-rpath=/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/libpfm4/lib:/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src,--enable-new-dtags 
make[1]: Leaving directory '/home/wcohen/rpmbuild/BUILD/papi-7.1.0/src/components/cuda/tests'

```

**Comment by wcohen** [comment] 2024-09-25 18:27
This is the patch that was used to change the NVCC flags.  It isn't quite correct as it would still use position independent options even if they are not being used on the code compiled by GCC.

[papi-cuda_tests_pic.txt](https://github.com/user-attachments/files/17136724/papi-cuda_tests_pic.txt)

**Comment by wcohen** [comment] 2024-10-03 22:58
I tried out the 2024.09.cuda_tests_pic branch code and that does address the issue when building with shared libraries.

**Comment by Treece-Burgess** [comment] 2024-10-08 18:17
Closing issue as PR #251 resolves it.

**Closed by Treece-Burgess** 2024-10-08 18:17 UTC
